### ISSUE TITLE
Add OAuth example?

### ISSUE THREAD

**Issue by davoutuk** [zkoss/zkspringboot#10]
Can you add an Spring Security OAuth example to this excellent project?

**Comment by cor3000** [comment]
An OAuth example would be purely spring/spring boot specific and won't change any of ZK's usage (the URLs you would want to request would be the same independend of the security mechanism). So we are not planning to add this (it would only lead to a potentially out-dated example).

There are OAuth examples available around the web (e.g using the pack4j library). If you have a specifc problem using your favourite OAuth solution with ZK I'd recommend asking in our forums or contacting ZK Support directly.

https://www.zkoss.org/support
