### ISSUE TITLE
Templates - how to reference template source file locations?

### ISSUE THREAD

**Issue by davoutuk** [zkoss/zkspringboot#12]
I'm building my first ZK/Springboot app and have the index.zul page setup to use templates,  like:

```
<zk>
    <apply templateURI="/public/template_public.zul">
         <template name="header" src="/public/header_public.zul" />
         <template name="main" src="/public/main_index.zul" />
    </apply>
</zk>
```

The index.zul file is under a folder the 'resources/web/zul' folder,  and my templates files are under a folder 'resources/web/zul/public/'

The application.properties file has the line...
zk.homepage=zul/index

When I run this I get an error...
"Page not found: /public/template_public.zul"

Any suggestions to fix this?

**Comment by cor3000** [comment]
The way to reference templates and other resources on the classpath below the web folder is using the prefix "~./"

e.g.

<zk>
    <apply templateURI="~./zul/public/template_public.zul">
         <template name="header" src="~./zul/public/header_public.zul" />
         <template name="main" src="~./zul/public/main_index.zul" />
    </apply>
</zk>
