### ISSUE TITLE
spring security demo not working

### ISSUE THREAD

**Issue by davoutuk** [zkoss/zkspringboot#14]
I'm adapting the spring security demo module found here for my own project.

When I run my test to try and access a secured page, the process redirects to the '/login.zul' page but after I submit the login details things go really weird.

The app stop and shows a URL line of...

http://localhost:8080/zkau/web/a86feb42/zul/less/font/fontawesome-webfont.woff2?v=4.7.0

The web browser view is full of garbage characters like...

![image](https://user-images.githubusercontent.com/25985256/56129432-edfd6900-5f79-11e9-92d5-c06d92e5a29c.png)

Any ideas?

**Comment by davoutuk** [comment]
Fixed it!

Added 'font' to resources list

 private static final String[] ZK_RESOURCES = {"/zkau/web/**/js/**", "/zkau/web/**/font/**","/zkau/web/**/zul/css/**", "/zkau/web/**/img/**","/image/**"};

**Comment by cor3000** [comment]
thanks for the hint. Even though I never noticed that particular problem on my side (I assume the font was already cached) I'll add this resource path to the example:

    private static final String[] ZK_RESOURCES = {
            "/zkau/web/**/js/**",
            "/zkau/web/**/zul/css/**",
            "/zkau/web/**/font/**",
            "/zkau/web/**/img/**"
    };

**Comment by cor3000** [comment]
added in 
https://github.com/zkoss/zkspringboot/commit/bef9780a5f015002c1d1699dc89c9e3c38193ead
