### ISSUE TITLE
why is zkspringboot 2.3.1 unavailable in the ce maven repository now?

### ISSUE THREAD

**Issue by typik89** [zkoss/zkspringboot#17]

**Comment by cor3000** [comment]
I can't give you a reason why it was unavailable 40 mins ago, now I checked the links to the version and they work for me.

https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-starter/2.3.1/
https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-autoconfig/2.3.1/

if the problem persists please provide an error message or some kind of information about how it is not available.

**Comment by typik89** [comment]
It works, Thanks a lot

**Comment by cor3000** [comment]
thanks for getting back ... good to know our repository is available again, weird it was temporarily unreachable.
