### ISSUE TITLE
Cannot reference any files inside a .zul file

### ISSUE THREAD

**Issue by NickDelta** [zkoss/zkspringboot#18]
I am running Spring Boot 2.3.1 with zkspringboot-starter 2.3.1.RELEASE . My `application.properties` file is the one below:
```
zk.springboot-packaging=jar

zk.homepage=index
zk.zul-view-resolver-enabled=true
zk.zul-view-resolver-suffix=.zul
zk.websockets-enabled=true
zk.servlet3-push-enabled=true](url)
```

zul files are located under `resources/web` as described in your README file. 

The index.zul file contains references to other .zul files in the same directory . One such is : 
`<include id="header" sclass="header" src="header.zul" />`

When I try to load the page the following exception is thrown:

```
Servlet.service() for servlet [DHtmlUpdateServlet] threw exception

org.zkoss.zk.ui.UiException: Page not found: /header.zul
	at org.zkoss.zk.ui.http.ExecutionImpl.getPageDefinition(ExecutionImpl.java:385) ~[zk-9.0.0.1-Eval.jar:9.0.0.1]
	at org.zkoss.zul.Include.afterCompose(Include.java:509) ~[zul-9.0.0.1-Eval.jar:9.0.0.1]
.... more stack trace can be given if necessary 
```

Why can't ZK find files from the same directory? If the .zul file doesn't contain any references then it is displayed correctly.

**Comment by NickDelta** [comment]
I should have put `~./header.zul` .

**Comment by cor3000** [comment]
thanks for sharing you found a solution ... I'd have proposed the same.
