### ISSUE TITLE
how to implement error handling

### ISSUE THREAD

**Issue by typik89** [zkoss/zkspringboot#19]
How can I handle errors using zk spring boot starter?
I believe that the document isn't actual:
https://www.zkoss.org/wiki/ZK_Installation_Guide/Quick_Start/Create_and_Run_Your_First_ZK_Application_with_Spring_Boot

**Comment by typik89** [comment]
I understood that we can simply place erro.zul to src/main/resources/web

**Comment by cor3000** [comment]
Baby doesn't want to sleep yet.  I'll need a bit before I can connect.
