### ISSUE TITLE
zkspringboot-starter references a jar from evaluation repository

### ISSUE THREAD

**Issue by danlz** [zkoss/zkspringboot#27]
The zkspringboot-starter pom.xml references the zkbind from ZK Eval repository.
https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-starter/pom.xml#L69

Can you change the zkbind dependency to point to ZK CE repository?

**Comment by cor3000** [comment]
since it's a "starter" project it'll help you to get "started" quickly (the starter only contains dependencies NO code)
so if you know which versions you prefer you can just include the zkspringboot-autoconfig project on top of your desired springboot and zk versions

**Comment by danlz** [comment]
Yes, but it still would be nice to have clean dependencies in the starter.

**Comment by strangelookingnerd** [comment]
I second this. There is no reason to depend on the *-Eval versions. It won't help you to get started faster ;-)

**Comment by Yann39** [comment]
I agree, this should not reference any dependencies from the evaluation repository.
For the moment we simply exclude zkbind :
```xml
<dependency>
    <groupId>org.zkoss.zkspringboot</groupId>
    <artifactId>zkspringboot-starter</artifactId>
    <version>${zkspringboot.version}</version>
    <exclusions>
        <exclusion>
            <groupId>org.zkoss.zk</groupId>
            <artifactId>zkbind</artifactId>
        </exclusion>
    </exclusions>
    <type>pom</type>
</dependency>

<dependency>
    <groupId>org.zkoss.zk</groupId>
    <artifactId>zkbind</artifactId>
    <version>${zk.version}</version>
</dependency>
```
Else it fails in CI/CD production environment where we don't have the evaluation repository.

It could be nice to avoid this.

**Comment by hawkchen** [comment]
I have updated pom.xml of autoconfig and starter
