### ISSUE TITLE
How to config IdGeneratorClass in zkspringboot yml?

### ISSUE THREAD

**Issue by VincentLiSH** [zkoss/zkspringboot#30]
Pragmaticly setting  IdGeneratorClass has no effect ,like below:

```
@Configuration
@Profile({ "test" })
public class ZkDevProfileConfig {	
	@PostConstruct
	public void initDevelopmentProperties() throws Exception {		
		WebApps.getCurrent().getConfiguration().setIdGeneratorClass(StaticZkIdGenerator.class);
	}
}
```

**Comment by cor3000** [comment]
at this moment the the webapp has already been initialized by the configuration so changing the configuration doesn't affect the id generator instance.

from the [ZK API it looks](https://www.zkoss.org/javadoc/latest/zk/org/zkoss/zk/ui/sys/WebAppCtrl.html#setIdGenerator-org.zkoss.zk.ui.sys.IdGenerator-) like you can provide your own instance of an IdGenerator directly through the `WebAppCtrl` interface

https://github.com/zkoss/zk/blob/v9.6.1/zk/src/org/zkoss/zk/ui/sys/WebAppCtrl.java#L107

so what I'd try is something like:

`((WebAppCtrl) WebApps.getCurrent()).setIdGenerator(new StaticZkIdGenerator())`

and important don't forget to [disable UUID recycling](https://www.zkoss.org/wiki/ZK_Configuration_Reference/zk.xml/The_Library_Properties/org.zkoss.zk.ui.uuidRecycle.disabled)

**Comment by VincentLiSH** [comment]
Thanks , it worked.
