### ISSUE TITLE
Status: 403 Forbidden when using zaspringboot-starter in pom.xml

### ISSUE THREAD

**Issue by lcmuniz** [zkoss/zkspringboot#34]
I clone the repo and open zkspringboot-demo-jar in IntellJ but when build with maven thiis error occurs:

Could not transfer artifact org.zkoss.zkspringboot:zkspringboot-starter:pom:2.5.12 from/to ZK CE (https://mavensync.zkoss.org/maven2): authorization failed for https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-starter/2.5.12/zkspringboot-starter-2.5.12.pom, status: 403 Forbidden

This project requires authentication?

**Comment by benyaminl** [comment]
yeah, we need to change it into -Eval from -jakarta... and it's broken even after using -Eval.. sadly...

**Comment by benyaminl** [comment]
@lcmuniz This already fixed, you can retest it. Thanks to @mduchemin fixing the dependency.
