### ISSUE TITLE
JARs missing or corrupted in ZK maven repository

### ISSUE THREAD

**Issue by AleixMT** [zkoss/zkspringboot#45]
Hello. I am using zkspringboot as dependency in my project. I was using version 1.0.4. This version worked great and is stored in [here](https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-starter/), in a custom repository of the ZK framework. 

This is what the folder of the version 1.0.4 contained: 
![image](https://github.com/zkoss/zkspringboot/assets/23342150/fed9e629-ba4a-40b7-ac66-7a87ede7de78). Everything worked great.

But, for example, if you try to upgrade to version 2.3.0 [the JAR that maven tries to download is corrupted](https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-starter/2.3.0/zkspringboot-starter-2.3.0.jar). Moreover, I noted that version 2.3.0 stopped including the source code JAR files:

![image](https://github.com/zkoss/zkspringboot/assets/23342150/ea41095c-90dd-4cca-8766-a1c1a7bf9430)

Why?

In next releases, there are not JAR files included in the version, not for source code, not as binary that I can use, only the POM:

![image](https://github.com/zkoss/zkspringboot/assets/23342150/70bc052e-869a-4f4f-8ee3-4d6dfbce6b76)

[Note that in the springboot / ZK tutorial you are recommending uisng the latest version of zkspringboot artifact](https://www.zkoss.org/wiki/ZK_Installation_Guide/Quick_Start/Create_and_Run_Your_First_ZK_Application_with_Spring_Boot).

![image](https://github.com/zkoss/zkspringboot/assets/23342150/d57ce1ca-ccd4-4991-9743-bc8c2bd9548f)

If this is a mistake could you please fix it? If it is not, can you explain me how should I use zkspringboot in releases after 1.0.4? 

Thank you so much for yor time.

**Comment by cor3000** [comment]
hi,

there is no code in zkspringboot-_starter_ ... it's only a pom file declaring a working configuration to get _started_ easily
the actual configuration code is in zkspringboot-autoconfig.jar

the fact that there are dummy or empty or corrupted pom files in this dependency was a side effect of limited build/deploy scripts at the time. which has been corrected in version 3.0.0 apparently.

zkspringboot-starter is just a pom file (usable as a maven parent or bom include) - there was never a reasonable content, an should not have been (sorry about the confusion)
if you already know which other dependencies you are going to use (zk version, spring version) please just use zkspringboot-autoconfig, which contains spring configuration classes to initialize ZK with default but adjustable configuration

**Comment by AleixMT** [comment]
Okay, thank you so much @cor3000 for your answer. I was not proceeding correctly. Now I have added zkspringboot-starter as dependency of my project and also zkplus, which is the only part of ZK that I am using. Now everything is working as expected. I close this issue as solved. Thank you!
