### ISSUE TITLE
DHtmlLayoutServlet initialization fails if the property zk.resource-uri is defined

### ISSUE THREAD

**Issue by pgid69** [zkoss/zkspringboot#48]
With Spring boot, we can't have both properties zk.update-uri and zk.resource-uri defined.
In the code 
https://github.com/zkoss/zkspringboot/blob/330190bab59b86f0fca28009621e242d81a8cbd1/zkspringboot-autoconfig/src/main/java/org/zkoss/zkspringboot/ZkAutoConfiguration.java#L45
It should be reg.addInitParameter() instead of reg.setInitParameters()

If both properties are defined org.zkoss.zk.ui.http.DHtmlLayoutServlet initialization fails because update-uri is not set

**Comment by hawkchen** [comment]
Thanks for reporting this issue. It was fixed at `3.2.6.1`
