### ISSUE TITLE
Throw Page not found Exception, but ZK display 500

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#8]
I try to throw page not found exception

throw new ResponseStatusException(HttpStatus.NOT_FOUND, Labels.getLabel("error._404.title"), new PageNotFoundException());

but client still recieve 500 error, How can I throw page not found in ZK Spring Boot?

**Comment by cor3000** [comment]
I just tested the [error customization](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/boot-features-developing-web-applications.html#boot-features-error-handling-custom-error-pages) in spring boot which works as described.

I created a file 404.html in:
`src/main/resources/public/error/404.html`

Then accessing a non mapped path displays this message.

Sending a 404 from within a ZK application seems unusual. Once you are inside your ZK controller it means the zul page/controller was already found so a 404 seems unusual to me. Maybe you can elaborate where you are trying to send a 404 from.

If you can provide the stack trace of the exception it might help to identify where you are throwing an exception.

**Comment by cor3000** [comment]
no reproducing information provided, default spring boot config works
